apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datagent-ingress
spec:
  rules:
  - host: api.datagent.avaloka.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: datagent-inference
            port:
              number: 8000
